[package]
name = "dcs"
description = "data connected service"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
opcua = "0.12.0"
pico-args = "0.5.0"
kafka = "0.10.0"
tokio = { version = "1", features = ["full"] }
